// FOR CONFIG
export const LIST_CONFIG='LIST_CONFIG';
export const ADD_CONFIG='ADD_CONFIG';
export const EDIT_CONFIG='EDIT_CONFIG';
export const REMOVE_CONFIG='REMOVE_CONFIG';
// FOR CONFIG
// FOR STORES
export const LIST_PROJECT='LIST_PROJECT';
export const ADD_PROJECT='ADD_PROJECT';
export const ADD_DETAIL_PROJECT='ADD_DETAIL_PROJECT';
// FOR STORES

// FOR FACE KNOWNS
export const LIST_FACEKNOWN='LIST_FACEKNOWN';
export const ADD_FACEKNOWN='ADD_FACEKNOWN';
export const EDIT_FACEKNOWN='EDIT_FACEKNOWN';
export const REMOVE_FACEKNOWN='DELETE_FACEKNOWN';
// FOR FACE KNOWNS
